# Generated by Django 3.1.5 on 2021-01-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(blank=True, max_length=5, verbose_name='Белки')),
                ('fats', models.CharField(blank=True, max_length=5, verbose_name='Жиры')),
                ('carb', models.CharField(blank=True, max_length=5, verbose_name='Углеводы')),
                ('cals', models.CharField(blank=True, max_length=5, verbose_name='Каллорийность')),
                ('weight', models.CharField(blank=True, max_length=5, verbose_name='Вес нетто')),
                ('pack', models.CharField(blank=True, max_length=5, verbose_name='Упаковка')),
                ('num_per_block', models.CharField(blank=True, max_length=5, verbose_name='Количество в блоке')),
                ('storage_period', models.CharField(blank=True, max_length=5, verbose_name='Срок хранения')),
                ('manufacturer', models.CharField(blank=True, max_length=30, verbose_name='Произовдитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='shop.product')),
            ],
        ),
    ]
