# Generated by Django 3.1.5 on 2021-01-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcharacters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacters',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='shop.product'),
        ),
    ]
